const books = [
    { name: "Academy Scroll", type: "Spellbook", rarity: "Uncommon", description: "Contains the following spells: Great Glintstone Shard, Swift Glintstone Shard" },
    { name: "Conspectus Scroll", type: "Spellbook", rarity: "Rare", description: "Contains the following spells: Glintstone Cometshard, Star Shower" },
    { name: "Royal House Scroll", type: "Spellbook", rarity: "Uncommon", description: "Contains the following spells: Glintblade Phalanx, Carian Slicer, Mage Armor, Shield, Arcane Sword" },
    { name: "Two Fingers Prayerbook", type: "Spellbook", rarity: "Rare", description: "Contains the following spells: Lord's Heal, Lord's Aid, Augury, Find Traps, Locate Object" },
    { name: "Assassin's Prayerbook", type: "Spellbook", rarity: "Uncommon", description: "Contains the following spells: Assassin's Approach, Darkness, Silence" },
    { name: "Golden Order Principia", type: "Spellbook", rarity: "Very Rare", description: "Contains the following spells: Radagon's Rings of Light, Law of Regression, Divine Favor" },
    { name: "Dragon Cult Prayerbook", type: "Spellbook", rarity: "Rare", description: "Contains the following spells: Lightning Spear, Honed Bolt, Electrify Armament, Call Lightning" },
    { name: "Ancient Dragon Prayerbook", type: "Spellbook", rarity: "Very Rare", description: "Contains the following spells: Ancient Dragons' Lightning Spear, Ancient Dragons' Lightning Strike" },
    { name: "Fire Monks' Prayerbook", type: "Spellbook", rarity: "Uncommon", description: "Contains the following spells: O, Flame!, Surge, O Flame!, Burning Hands" },
    { name: "Giant's Prayerbook", type: "Spellbook", rarity: "Rare", description: "Contains the following spells: Giants Flame Take Thee, Flame Fall Upon Them, Firestorm" },
    { name: "Godskin Prayerbook", type: "Spellbook", rarity: "Rare", description: "Contains the following spells: Longarms, Blackfire Storm, Blackflame Blade, Black Flame" },
    { name: "Ancient Dragon Apostle's Cookbook [1]", type: "Cookbook", rarity: "Uncommon", description: "Lightning Grease (1 Root Resin, 1 Fulgurbloom), Lightning Ammunition x10 (1 Beast Carcass, 1 Fulgurbloom)" },
    { name: "Ancient Dragon Apostle's Cookbook [2]", type: "Cookbook", rarity: "Uncommon", description: "Lightning Pot (1 Cracked Pot, 1 Mushroom, 1 Fulgurbloom)" },
    { name: "Ancient Dragon Apostle's Cookbook [3]", type: "Cookbook", rarity: "Rare", description: "Dragonwound Grease (1 Root Resin, 1 Beast Carcass, 1 Gravel Stone)" },
    { name: "Ancient Dragon Apostle's Cookbook [4]", type: "Cookbook", rarity: "Rare", description: "Ancient Dragonbolt Pot (1 Ritual Pot, 2 Mushroom, 1 Fulgurbloom, 1 Gravel Stone), Lightningproof Dried Liver (3 Rowa Fruit, 1 Beast Carcass, 1 Fulgurbloom)" },
    { name: "Armorer's Cookbook [1]", type: "Cookbook", rarity: "Uncommon", description: "Fire Grease (1 Root Resin, 1 Smoldering Butterfly), Fireproof Dried Liver (1 Rowa Fruit, 1 Beast Carcass, 1 Smoldering Butterfly)" },
    { name: "Armorer's Cookbook [2]", type: "Cookbook", rarity: "Uncommon", description: "Fire Ammunition x10 (1 Beast Carcass, Smoldering Butterfly), Neutralizing Boluses (1 Herba, 1 Cave Moss, 1 Great Dragonfly Head)" },
    { name: "Armorer's Cookbook [3]", type: "Cookbook", rarity: "Uncommon", description: "Exalted Flesh (5 Rowa Fruit, 1 Beast Carcass, 1 Arteria Leaf)" },
    { name: "Armorer's Cookbook [4]", type: "Cookbook", rarity: "Uncommon", description: "Redmane Fire Pot (1 Ritual Pot, 2 Mushroom, 1 Smoldering Butterfly, 1 Old Fang)" },
    { name: "Armorer's Cookbook [5]", type: "Cookbook", rarity: "Rare", description: "Immunizing Cured Meat (3 Rowa Fruit, 1 Beast Carcass, 1 Great Dragonfly Head, 1 Smoldering Butterfly), Immunizing White Cured Meat (3 Rowa Fruit, 1 Strip of White Flesh, 1 Great Dragonfly Head, 1 Smoldering Butterfly)" },
    { name: "Armorer's Cookbook [6]", type: "Cookbook", rarity: "Rare", description: "Preserving Boluses (2 Herba, 1 Cave Moss, 1 Sacramental Bud)" },
    { name: "Armorer's Cookbook [7]", type: "Cookbook", rarity: "Rare", description: "Giantsflame Fire Pot (1 Ritual Pot, 2 Fire Blossom)" },
    { name: "Fevor's Cookbook [1]", type: "Cookbook", rarity: "Uncommon", description: "Sleep Pot (1 Cracked Pot, 1 Mushroom, 1 Trina's Lily)" },
    { name: "Fevor's Cookbook [2]", type: "Cookbook", rarity: "Uncommon", description: "Soporific Grease (1 Root Resin, 1 Trina's Lily), Sleepbone Ammunition x10 (1 Beast Carcass, Trina's Lily)" },
    { name: "Fevor's Cookbook [3]", type: "Cookbook", rarity: "Rare", description: "Bewitching Branch (1 Sacramental Bud, 1 Miquella's Lily)" },
    { name: "Frenzied's Cookbook [1]", type: "Cookbook", rarity: "Uncommon", description: "Clarifying Boluses (2 Herba, 1 Cave Moss, 1 Eye of Yelough)" },
    { name: "Frenzied's Cookbook [2]", type: "Cookbook", rarity: "Uncommon", description: "Frenzyflame Stone (1 Eye of Yelough, 1 Sanctuary Stone)" },
    { name: "Glintstone Craftsman's Cookbook [1]", type: "Cookbook", rarity: "Uncommon", description: "Cuckoo Glintstone (1 Crystal Bud, 1 Cracked Crystal)" },
    { name: "Glintstone Craftsman's Cookbook [2]", type: "Cookbook", rarity: "Uncommon", description: "Freezing Grease (1 Root Resin, 1 Rimed Crystal Bud)" },
    { name: "Glintstone Craftsman's Cookbook [3]", type: "Cookbook", rarity: "Uncommon", description: "Albinauric Pot (1 Ritual Pot, 2 Mushroom, 1 Albinauric Bloodclot)" },
    { name: "Glintstone Craftsman's Cookbook [4]", type: "Cookbook", rarity: "Uncommon", description: "Magic Pot (1 Cracked Pot, 2 Shimmering Firefly), Shield Grease (1 Root Resin, 1 Silver Tear Husk, 1 Crystal Bud)" },
    { name: "Glintstone Craftsman's Cookbook [5]", type: "Cookbook", rarity: "Uncommon", description: "Magic Grease (1 Root Resin, 1 Crystal Bud), Magic Ammunition x10 (1 Beast Carcass, 2 Shimmering Firefly)" },
    { name: "Glintstone Craftsman's Cookbook [6]", type: "Cookbook", rarity: "Rare", description: "Freezing Pot (1 Ritual Pot, 2 Rimed Crystal Bud)" },
    { name: "Glintstone Craftsman's Cookbook [7]", type: "Cookbook", rarity: "Rare", description: "Cold Ammunition x10 (1 Beast Carcass, 3 Rimed Crystal Bud)" },
    { name: "Glintstone Craftsman's Cookbook [8]", type: "Cookbook", rarity: "Rare", description: "Academy Magic Pot (1 Ritual Pot, 2 Shimmering Firefly, 1 Old Fang)" },
    { name: "Missionary's Cookbook [1]", type: "Cookbook", rarity: "Uncommon", description: "Holy Water Pot (1 Cracked Pot, 1 Mushroom, 1 Tarnished Blossom)" },
    { name: "Missionary's Cookbook [2]", type: "Cookbook", rarity: "Uncommon", description: "Scriptstone (1 Ruin Fragment), Gold-Pickled Fowl Foot (3 Rowa Fruit, 1 Four-Toed Fowl Foot, 1 Shimmering Firefly)" },
    { name: "Missionary's Cookbook [3]", type: "Cookbook", rarity: "Uncommon", description: "Silver-Pickled Fowl Foot (3 Rowa Fruit, 1 Four-Toed Fowl Foot, 1 Shimmering Firefly)" },
    { name: "Missionary's Cookbook [4]", type: "Cookbook", rarity: "Uncommon", description: "Holy Grease (1 Root Resin, 1 Tarnished Golden Sunflower), Golden Ammunition x10 (1 Beast Carcass, 2 Tarnished Golden Sunflower)" },
    { name: "Missionary's Cookbook [5]", type: "Cookbook", rarity: "Rare", description: "Sacred Order Pot (1 Ritual Pot, 2 Mushroom, 1 Tarnished Golden Sunflower, 1 Golden Centipede)" },
    { name: "Missionary's Cookbook [6]", type: "Cookbook", rarity: "Rare", description: "Holyproof Dried Liver (5 Rowa Fruit, 1 Beast Carcass, 3 Tarnished Golden Sunflower)" },
    { name: "Missionary's Cookbook [7]", type: "Cookbook", rarity: "Rare", description: "Rejuvenating Boluses (2 Herba, 1 Cave Moss, 1 Golden Centipede)" },
    { name: "Nomadic Warrior's Cookbook [1]", type: "Cookbook", rarity: "Common", description: "Arrow x10 (1 Beast Carcass), Bolt x10 (1 Beast Carcass)" },
    { name: "Nomadic Warrior's Cookbook [2]", type: "Cookbook", rarity: "Common", description: "Glowstone (1 Ruin Fragment, 1 Herba), Invigorating Cured Meat (3 Rowa Fruit, 1 Beast Carcass, 1 Crab Eggs, 1 Land Octopus Ovary), Invigorating White Cured Meat (3 Rowa Fruit, 1 Strip of White Flesh, 1 Crab Eggs, 1 Land Octopus Ovary)" },
    { name: "Nomadic Warrior's Cookbook [3]", type: "Cookbook", rarity: "Common", description: "Pickled Turtle Neck (3 Rowa Fruit, 1 Turtle Neck Meat, 1 Herba), Poisonbone Ammunition x10 (1 Beast Carcass, 1 Poisonbloom)" },
    { name: "Nomadic Warrior's Cookbook [4]", type: "Cookbook", rarity: "Common", description: "Fetid Pot (1 Cracked Pot, 1 Mushroom, 1 Golden Dung)" },
    { name: "Nomadic Warrior's Cookbook [5]", type: "Cookbook", rarity: "Common", description: "Beastlure Pot (1 Ritual Pot, 1 Beast Carcass, 2 Beast Carcass)" },
    { name: "Nomadic Warrior's Cookbook [6]", type: "Cookbook", rarity: "Common", description: "Blood Grease (1 Root Resin, 1 Bloodrose), Bloodbone Ammunition x10 (3 Beast Carcass, 1 Bloodrose)" },
    { name: "Nomadic Warrior's Cookbook [7]", type: "Cookbook", rarity: "Common", description: "Stanching Boluses (1 Herba, 1 Cave Moss, 1 Land Octopus Ovary), Soft Cotton (3 Rowa Fruit, 1 Smoldering Butterfly), Rainbow Stone Ammunition (1 Beast Carcass, 3 Ruin Fragment)" },
    { name: "Nomadic Warrior's Cookbook [8]", type: "Cookbook", rarity: "Common", description: "Poison Grease (1 Root Resin, 1 Poisonbloom)" },
    { name: "Nomadic Warrior's Cookbook [9]", type: "Cookbook", rarity: "Common", description: "Rancor Pot (1 Cracked Pot, 2 Grave Violet)" },
    { name: "Nomadic Warrior's Cookbook [10]", type: "Cookbook", rarity: "Uncommon", description: "Stormwing Ammunition x10 (1 Beast Carcass, 1 Stormhawk Feather)" },
    { name: "Nomadic Warrior's Cookbook [11]", type: "Cookbook", rarity: "Uncommon", description: "Crystal Dart (3 Cracked Crystal), Spellproof Dried Liver (3 Rowa Fruit, 1 Beast Carcass, 2 Shimmering Firefly), Shattershard Arrow (3 Beast Carcass, 2 Cracked Crystal)" },
    { name: "Nomadic Warrior's Cookbook [12]", type: "Cookbook", rarity: "Uncommon", description: "Cursed-Blood Pot (1 Ritual Pot, 2 Mushroom, 1 Beast Carcass, 1 Bloodrose)" },
    { name: "Nomadic Warrior's Cookbook [13]", type: "Cookbook", rarity: "Uncommon", description: "Greatarrow x10 (1 Beast Carcass)" },
    { name: "Nomadic Warrior's Cookbook [14]", type: "Cookbook", rarity: "Uncommon", description: "Poison Pot (1 Cracked Pot, 1 Mushroom, 1 Poisonbloom), Roped Poison Pot (1 Cracked Pot, 1 Mushroom, 1 Poisonbloom), Poisonbone Dart" },
    { name: "Nomadic Warrior's Cookbook [15]", type: "Cookbook", rarity: "Uncommon", description: "Rotbone Ammunition x10 (1 Beast Carcass, 1 Aeonian Butterfly)" },
    { name: "Nomadic Warrior's Cookbook [16]", type: "Cookbook", rarity: "Uncommon", description: "Thawfrost Boluses (1 Herba, 1 Cave Moss, 1 Crab Eggs), Stimulating Boluses (1 Herba, 1 Cave Moss, 1 Slumbering Egg)" },
    { name: "Nomadic Warrior's Cookbook [17]", type: "Cookbook", rarity: "Uncommon", description: "Soap (2 Mushroom), Oil Pot (1 Cracked Pot, 1 Mushroom)" },
    { name: "Nomadic Warrior's Cookbook [18]", type: "Cookbook", rarity: "Uncommon", description: "Dappled Cured Meat (5 Rowa Fruit, 1 Beast Carcass, 1 Beast Carcass, 1 Nascent Butterfly), Dappled White Cured Meat (5 Rowa Fruit, 1 Strip of White Flesh, 1 Beast Carcass, 1 Nascent Butterfly)" },
    { name: "Nomadic Warrior's Cookbook [19]", type: "Cookbook", rarity: "Uncommon", description: "Sweet Raisin (1 Rowa Fruit), Warming Stone (1 Erdleaf Flower, 1 Smoldering Butterfly, 1 Sanctuary Stone)" },
    { name: "Nomadic Warrior's Cookbook [20]", type: "Cookbook", rarity: "Uncommon", description: "Volcano Pot (1 Cracked Pot, 2 Volcanic Stone)" },
    { name: "Nomadic Warrior's Cookbook [21]", type: "Cookbook", rarity: "Uncommon", description: "Alluring Pot (1 Ritual Pot, 1 Albinauric Bloodclot)" },
    { name: "Nomadic Warrior's Cookbook [22]", type: "Cookbook", rarity: "Rare", description: "Rot Pot (1 Ritual Pot, 2 Mushroom, 2 Faded Erdleaf Flower, 1 Aeonian Butterfly), Rot Grease (1 Root Resin, 1 Aeonian Butterfly)" },
    { name: "Nomadic Warrior's Cookbook [23]", type: "Cookbook", rarity: "Rare", description: "Frozen Raisin (1 Rowa Fruit), Clarifying Cured Meat (5 Rowa Fruit, 1 Beast Carcass, 1 Slumbering Egg, 1 Eye of Yelough), Clarifying White Cured Meat (1 Rowa Fruit, 1 Strip of White Flesh, 1 Slumbering Egg, 1 Eye of Yelough)" },
    { name: "Nomadic Warrior's Cookbook [24]", type: "Cookbook", rarity: "Rare", description: "Swarm Pot (1 Cracked Pot, 1 Mushroom, 1 Golden Dung)" },
    { name: "Perfumer's Cookbook [1]", type: "Cookbook", rarity: "Uncommon", description: "Spark Aromatic (1 Perfume Bottle, 1 Altus Bloom, 1 Miranda Powder), Uplifting Aromatic (1 Perfume Bottle, 1 Altus Bloom, 1 Cave Moss, 1 Silver Tear Husk, 1 Arteria Leaf)" },
    { name: "Perfumer's Cookbook [2]", type: "Cookbook", rarity: "Uncommon", description: "Poison Spraymist (1 Perfume Bottle, 1 Altus Bloom, 1 Miranda Powder, 1 Poisonbloom), Bloodboil Aromatic (1 Perfume Bottle, 2 Altus Bloom, 1 Cave Moss, 1 Land Octopus Ovary, 1 Arteria Leaf)" },
    { name: "Perfumer's Cookbook [3]", type: "Cookbook", rarity: "Rare", description: "Ironjar Aromatic (1 Perfume Bottle, 2 Altus Bloom, 1 Cave Moss, 3 Living Jar Shard)" },
    { name: "Perfumer's Cookbook [4]", type: "Cookbook", rarity: "Rare", description: "Acid Spraymist (1 Perfume Bottle, 1 Altus Bloom, 1 Miranda Powder, 4 Formic Rock)" }
];