const subclasses = [
    {
        name: "Path of the Stormhawk",
        className: "Barbarian",
        description: "A path for barbarians who channel the sweeping gales of Stormhill. They form protective barriers of wind and unleash the electric charge of storms upon their foes.",
        features: [
            {
                name: "Gale Aura",
                level: 3,
                description: "When you select this feature at 3rd level, the gale winds of Stormhill form a protective barrier around when you rage. The gale extends in a 5-foot radius around you. The sweeping winds are difficult terrain for creatures of your choice and provide half-cover for you against ranged weapon attacks."
            },
            {
                name: "Jolt",
                level: 3,
                description: "Starting at 3rd level, you can store the electric charge generated by your storm to unleash on your foes later. When a creature you can see moves into a space within 10 feet of you or starts its turn there, you can use your reaction to deal 3 (1d4) lightning damage to that creature. The lightning damage increases to 4 (1d6) at 6th level, 5 (1d8) at 10th level, and 6 (1d10) at 14th level."
            },
            {
                name: "Galeforce",
                level: 6,
                description: "At 6th level, your storm grows in potency. The gale extends to a 10-foot radius. When you hit a creature with a melee attack while raging, you may attempt to take control of your storm to shove them as a bonus action."
            },
            {
                name: "Lightning Storm",
                level: 10,
                description: "At 10th level, your gale becomes a true storm crackling with electricity. While raging, your melee attacks deal an additional 5 (1d8) lightning damage."
            },
            {
                name: "Thunderclap",
                level: 10,
                description: "At 10th level, when you enter a rage, each creature of your choice within your storm must succeed on a Constitution saving throw or take 11 (2d10) thunder damage. The DC for the saving throw is 8 + your proficiency bonus + your Constitution modifier."
            },
            {
                name: "Storm King",
                level: 14,
                description: "At 14th level, your storm is perfected, a match for the Stormlords of old. Your gale expands to a 15-foot radius around you, providing three-quarters cover to you and half-cover to creatures of your choice within it. You also gain a fly speed equal to your movement speed while raging."
            }
        ]
    },
    {
        name: "Frenzied",
        className: "Bard",
        description: "A bardic college that has glimpsed the maddening light of the Three Fingers. They weave songs that inspire through terror, offering potent but dangerous visions of madness.",
        features: [
            {
                name: "Bonus Proficiencies",
                level: 3,
                description: "At 3rd-level, you glimpse a distant light. You gain proficiency in the Perception skill and have advantage on Perception checks made to see distant objects."
            },
            {
                name: "Maddened Inspiration",
                level: 3,
                description: "At 3rd level, you can offer a more potent inspiration, though you risk breaking the minds of your fellows. When you give Bardic Inspiration to a creature, you can impart a vision of madness with it. The creature takes psychic damage equal to the inspiration die you impart when they receive this special inspiration.\n\n- When a creature uses this special inspiration and rolls a 1 on the die, they can immediately roll the same die again and add the sum of both to the roll.\n- If the target rolls the maximum value on the inspiration die, they regain hit points equal to the value they rolled."
            },
            {
                name: "Soothing Song",
                level: 6,
                description: "At 6th level, you can play a song that abates the madness that grows within your mind. You have resistance to psychic damage and have advantage on saving throws against the stunned condition. When you use your Countercharm ability, creatures affected by the song gain the same benefits for the duration of the song."
            },
            {
                name: "Guiding Light",
                level: 10,
                description: "At 10th level, the distant light becomes whole, illuminating heretical truths. Your proficiency bonus is doubled for Perception checks. If your proficiency bonus for Perception checks is already doubled, you may choose another skill check you are proficient in to bolster instead. When you make a Wisdom saving throw, you may instead use your Perception (Wisdom) bonus instead of your normal modifier."
            },
            {
                name: "Frozen Frenzy",
                level: 10,
                description: "Also at 10th level, if a creature would be stunned by a spell or ability you use, they are paralyzed instead."
            },
            {
                name: "Shabriri's Cunning",
                level: 14,
                description: "Starting at 14th level, you are immune to psychic damage and the Stunned condition. Granting bardic inspiration through your Maddened Inspiration feature no longer deals psychic damage."
            },
            {
                name: "Lord of Frenzied Flame",
                level: 14,
                description: "The touch of the Three Fingers bestows clarity and vision to those who surrender themselves to Frenzy. If you have been touched by the Three Fingers, then any creature with your Bardic Inspiration dice has advantage on Wisdom saving throws. When they expend your Bardic Inspiration, they automatically roll the highest number possible."
            }
        ]
    },
    {
        name: "Two-Fingers Domain",
        className: "Cleric",
        description: "A domain for assassins of the Roundtable Hold. Originally purposed for keeping secrets and eliminating targets for the church, they now serve the Two Fingers as hunters of those who stray from guidance.",
        features: [
            {
                name: "Bonus Proficiencies",
                level: 1,
                description: "At 1st level, you gain proficiency with martial weapons and the Stealth skill."
            },
            {
                name: "Subtle Attack",
                level: 1,
                description: "At 1st level, you train in the arts of covert operations and assassination. Once per turn, when you hit with an attack, you can deal an extra 4 (1d6) damage to the creature you hit if you have advantage on the Attack roll. The attack must be a spell attack or use a finesse weapon.\n\nYou don't need advantage on the Attack roll if another enemy of the target is within 5 feet of it, that enemy isn't Incapacitated, and you don't have disadvantage on the Attack roll.\n\nThis damage increases to 7 (2d6) at 6th level, 11 (3d6) at 11th level, and 14 (4d6) at 16th level."
            },
            {
                name: "Channel Divinity: Blade in the Dark",
                level: 2,
                description: "Starting at 2nd level, you can use your Channel Divinity to beseech the Two Fingers for a cloak of shadow.\n\nAs an action, you can expend a use of Channel Divinity to project a gloamy ward in a 15-foot radius sphere that moves with you. The ward remains for 10 minutes. You and creatures of your choice within the area have advantage on Stealth checks for the duration. If a surprised creature would make a saving throw against a spell you cast, it makes the save at disadvantage if they are within the ward. You may dismiss the ward as an action on your turn."
            },
            {
                name: "Heretic Hunter",
                level: 6,
                description: "Since the shattering, the graceless masses have wandered the lands between. At level 6, your duties expand to hunting those the Erdtree shuns. You have advantage on Intelligence checks made to recall information about non-human humanoids.\n\nWhen you hit a non-human humanoid with an attack, or if a non-human humanoid fails a saving throw against a spell you cast, that creature has disadvantage on attack rolls against you until the beginning of your next turn."
            },
            {
                name: "Divine Strike",
                level: 8,
                description: "At 8th level, you gain the ability to infuse your weapon strikes with divine light — a gift from your deity. Once on each of your turns when you hit a creature with a weapon attack, you can cause the attack to deal an extra 5 (1d8) radiant damage to the target. When you reach 14th level, the extra damage increases to 9 (2d8)."
            },
            {
                name: "Order's Mark",
                level: 17,
                description: "Starting at 17th level, enemies you designate for destruction wilt under the combined efforts of you and your allies. If you hit a creature with a spell attack or deal radiant damage to one with a weapon attack, you can curse the target until the start of your next turn. The next time one of your allies hits the cursed creature with an attack, the target also takes 9 (2d8) psychic damage, and the curse ends. You can curse a creature in this way only once per turn."
            }
        ]
    },
    {
        name: "Prophecy Domain",
        className: "Cleric",
        description: "A domain for seers who have glimpsed visions of the Erdtree burning or other terrifying prophecies. They draw power from the ruinous flame of their visions.",
        features: [
            {
                name: "Bonus Proficiencies",
                level: 1,
                description: "At 1st level, you gain proficiency with martial weapons and the Insight skill."
            },
            {
                name: "Distant Visions",
                level: 1,
                description: "At 1st level, when you cast a spell that deals fire damage, you regain hit points equal to the level of the spell. When you cast a spell that restores hit points to a creature, you may take fire damage equal to your proficiency bonus to reroll one of the dice and restore the higher of the two. This damage cannot be reduced in any way."
            },
            {
                name: "Channel Divinity: Foretell Flame",
                level: 2,
                description: "Starting at 2nd level, you can use your Channel Divinity to recall the burning Erdtree in your visions, empowering flame you summon in its image.\n\nWhen you roll fire damage, you can use your Channel Divinity to deal maximum damage, instead of rolling."
            },
            {
                name: "Heretical Visions",
                level: 6,
                description: "At 6th level, you can project your visions of calamity into the future. When you use the Ready action to hold a spell, you do not need to concentrate while holding the spell. You must still concentrate on the spell after you release it if it would normally require it.\n\nIf you reach your next turn before releasing the spell, you regain the expended spell slot/points used to cast it."
            },
            {
                name: "Potent Spellcasting",
                level: 8,
                description: "Starting at 8th level, you add your Wisdom modifier to the damage you deal with any cleric cantrip."
            },
            {
                name: "Prophecy Fulfilled",
                level: 17,
                description: "Dreams of the Erdtree aflame haunt your waking mind constantly, threatening to come to fruition at any point. At 17th level, as an action you may summon an effigy of the burning erdtree in an unoccupied space you can see within 30 feet of you. You must concentrate on this effigy as if you had cast a spell. Each creature of your choice within 30 feet of the effigy has vulnerability to fire damage. The effigy lasts for 1 minute or until you lose concentration."
            }
        ]
    },
    {
        name: "Ancestral Follower",
        className: "Druid",
        description: "A druidic circle focusing on the worship of ancient spirits. They are expert marksmen who eschew metal and embrace the natural cycle of life from death.",
        features: [
            {
                name: "Hunter on High",
                level: 2,
                description: "The horned folk under the earth are expert marksmen. When you choose this circle at 2nd level, you become proficient with shortbows, longbows, and greatbows. Attacking at long range doesn't impose disadvantage on your ranged weapon attack rolls with those weapons."
            },
            {
                name: "Life from Death",
                level: 2,
                description: "You beckon the spirit of a fallen beast to come to your side. As a bonus action, you can expend a use of your wildshape to call a spirit that takes the form of a beast that you could assume the shape of. The spirit appears in an unoccupied space of your choice that you can see within 30 feet of you. The spirit is friendly to you and your companions and obeys your commands.\n\nIn combat, the spirit shares your initiative count, but it takes its turn immediately after yours. The only action it takes on its turn is the Dodge action, unless you take a bonus action on your turn to command it to take another action.\n\nThe spirit manifests for 1 hour, until it is reduced to 0 hit points, until you are incapacitated, or until you use this feature to summon the spirit again."
            },
            {
                name: "Ancestral Recall",
                level: 6,
                description: "At 6th level, you share a piece of yourself with the creatures you summon, a piece you can recall in a time of need. As a bonus action, you can teleport to a space occupied by a creature you have summoned or created. The summoned creature vanishes in the same moment and must be resummoned again."
            },
            {
                name: "Farstride",
                level: 10,
                description: "At 10th level, your arrows can beckon spirits on your behalf. As an action, you can fire a projectile from a ranged weapon towards a point within its range. As part of the same action, you can cast summon a creature in the target space using your Life from Death feature or a conjuration spell that summons a single creature."
            },
            {
                name: "Perfect Cycle",
                level: 14,
                description: "At 14th level, the scraps of life that keep your summoned creatures alive can be siphoned to maintain yourself. When you teleport using your farstride ability, you regain hit points equal to the current hit points of the target creature."
            }
        ]
    },
    {
        name: "Crucible Knight",
        className: "Fighter",
        description: "An elite martial archetype reflecting the strongest knights of Godfrey. They possess an indomitable will and wield the magical heritage of the primordial crucible.",
        features: [
            {
                name: "Stalwart",
                level: 3,
                description: "The crucible knights are the strongest knights of Godfrey. While you cannot match their strength yet, you can draw upon their indomitable will. At 3rd level, you gain advantage on skill checks and saving throws to avoid being knocked prone, shoved, or grappled. You must be wearing heavy armor to gain this advantage.\n\nYou also have trained in the art of fighting in heavy armor as well. You ignore the strength requirements of heavy amor, and wearing heavy armor does not impose disadvantage on Stealth checks for you."
            },
            {
                name: "Crucible Aspects",
                level: 3,
                description: "Other crucible knights throughout the Lands Between carry the magical heritage of the crucible. These Aspects of the Crucible allow the user to take on beastial aspects in combat. At 3rd level, you can use these aspects despite your potential lack of magical talents. You may prepare any number of Aspect of the Crucible incantations that you have discovered. You may cast each of these spells without spending spell points once per long rest. When you use an Action Surge, you may cast an Aspect of the Crucible spell without spending spell points as well. Constitution is your spellcasting ability for these spells."
            },
            {
                name: "Great Tree Guardian",
                level: 7,
                description: "The crucible knights are often sent to guard an individual or place, while others are sent as warriors to take on an offensive role. At 7th level, you may choose between the following options when you take a long rest. You may only benefit from one of these options at a time.\n\n**Guardian:** Choose a specific allied creature. While you are within five feet of the creature, it gains a +2 bonus to AC and can add 3 (1d4) to saving throws it makes. As a bonus action, you can move up to half your movement speed toward the allied creature.\n\n**Target:** Choose a specific hostile creature you can see. You can roll a d4 and add the number rolled to an attack roll or ability check it makes against the target creature. You can also add a d4 on saving throws against the target's spells or abilities."
            },
            {
                name: "Primordial Cycle",
                level: 17,
                description: "The number of true crucible knights number less than 20. At 17th level, you enter into these illustrious ranks. You have every Aspect of Crucible spell prepared constantly regardless of if you have discovered them. You can also cast these spells at will without expending a spell slot/points."
            }
        ]
    },
    {
        name: "Oath of Fundamentalism",
        className: "Paladin",
        description: "Paladins sworn to the Golden Order. They study the mathematical precision of the Erdtree's grace, describing the world through the concepts of regression and causality.",
        features: [
            {
                name: "Channel Divinity",
                level: 3,
                description: "When you take this oath at 3rd level, you gain the following two Channel Divinity options.\n\n**Call to Causality.** As a reaction to being hit by a melee attack, you can expend a use of Channel Divinity to retaliate against it. The creature takes damage equal to the damage dealt to you.\n\n**Call to Regression.** As an action, you can touch a willing creature and expend a use of Channel Divinity. If the creature is suffering from a condition, it can immediately make a new save against it. The creature can use your saving throw modifiers in place of its own."
            },
            {
                name: "Preceptual Study",
                level: 3,
                description: "The depths of the golden order are plumbed by fundamentalists, a fusion of religion and scholarship. When you take this oath at 3rd level, you may use Intelligence in place of Charisma for your paladin spells and abilities, including your Aura of Protection. You gain proficiency in the Nature and Survival skills if you don't already have it."
            },
            {
                name: "Aura of Order",
                level: 7,
                description: "Starting at 7th level, you have internalized the central concepts of the Golden Order. That knowledge alone creates an aura around you drawing others closer via regression. When a spell or condition affecting you or creatures of your choice in your aura ends, the affected creature gains advantage on the next attack roll, ability check, or saving throw they make before the end of their next turn.\n\nAt 18th level, the range of this aura increases to 30 feet."
            },
            {
                name: "Erdtree Rebirth",
                level: 15,
                description: "Central to the golden order is the Erdtrees role in the cycle of death and rebirth. Starting at 15th level, you recreate a small part of the Erdtree's magic in the same fashion. As an action, you can rejuvenate a creature you can see within 60 feet of you. The target regains all its hit points. The target can choose to end any conditions affecting it. If the target is prone, it can use its reaction to stand up. The target's severed limbs (fingers, legs, tails, and so on), if any, are restored as well.\n\nOnce you use this feature, you can't use it again until you finish a long rest."
            },
            {
                name: "Perfect Order Apotheosis",
                level: 20,
                description: "Having plumbed the depths of the golden order, you have discovered its truths and flaws. At 20th level, you can use a bonus action to contemplate this knowledge and use it to bolster yourself and others, gaining the following benefits for 1 minute:\n\n- You have resistance to force and radiant damage.\n- You have advantage on saving throws against spells.\n- Whenever you make an attack roll, an ability check, or a saving throw, you can treat a roll of 9 or lower on the d20 as a 10.\n- As an action, you can end any spell or condition affecting you. You may only remove one effect or condition per action spent.\n\nOnce you use this feature, you can't use it again until you finish a long rest."
            }
        ]
    },
    {
        name: "Oath of Dragon Tutelage",
        className: "Paladin",
        description: "Paladins who have learned the secrets of the ancient dragons, wielding red lightning and calling upon draconic might to smite their enemies.",
        features: [
            {
                name: "Channel Divinity",
                level: 3,
                description: "When you take this oath at 3rd level, you gain the following two Channel Divinity options.\n\n**Draconic Inspiration.** You can use your channel divinity to empower the incantations of your order. When you cast a Dragon Cult spell, you can expend a use of your channel divinity to increase your spell save DC for that spell by 2. You also gain advantage on any spell attack rolls for the incantation as well.\n\n**Dragonbolt.** Raise your blade to the sky and call down scarlet lightning to you. As a bonus action, you expend a use of channel divinity and empower yourself with the lightning of ancient dragons. For the next minute, your melee attacks deal an additional 4 (1d6) lightning damage, but you gain vulnerability to lightning damage for the duration."
            },
            {
                name: "Oath Spell",
                level: 3,
                description: "When you take this oath at 3rd level, you learn the *lightning spear* spell."
            },
            {
                name: "Aura of Dragon Tutelage",
                level: 7,
                description: "You have received secrets from the ancient dragons, secrets you can share with others. At 7th level, you emit an aura of crackling red lightning while you aren't incapacitated. You and any creatures of your choice within 10 feet have resistance to lightning damage, and advantage on saving throws against Dragon Cult incantation spells.\n\nAt 18th level, the range of this aura increases to 30 feet."
            },
            {
                name: "Dragonlord's Claw",
                level: 15,
                description: "The ancient dragon lord sleeps in the crumbling sky ruins. You have glimpsed his might in a shared dream. At 15th level, you may invoke the dragonlords claws when you smite a creature. As a bonus action, you may increase the reach of your melee weapon attacks by ten feet until the start of your next turn. If you use your Divine Smite during this time, it deals an additional 5 (1d8) lightning damage."
            },
            {
                name: "True Dragon",
                level: 20,
                description: "Having seen the dragon's lightning first hand, you can beckon the power of the true dragons. At 20th level, you can assume the form of a true dragon as an action, gaining the following benefits.\n\n- Wings sprout from your back and grant you a flying speed of 60 feet.\n- You have immunity to lightning damage.\n- Lightning damage you deal ignores damage resistance and damage immunities of creatures.\n- When you cast a Dragon Cult incantation, you can choose any number of creatures you can see. Those creatures are unaffected by the spell even if they are within its area of effect."
            }
        ]
    },
    {
        name: "Spirit Tuner",
        className: "Ranger",
        description: "Rangers who have a connection to the ashes of the deceased. They summon and direct spirits in combat, forging bonds with ethereal companions.",
        features: [
            {
                name: "Summon Beast",
                level: 3,
                description: "When you choose this subclass at 3rd level, you receive a spirit calling bell if you do not already have one. You also gain the *servant* ashes. These special spirit ashes do not exhaust themselves when summoned, and thus do not need to be rejuvenated by a spirit tuner."
            },
            {
                name: "Return from Ash",
                level: 3,
                description: "The spirits within ash speak to you, and you may, in turn, call them back from the world beyond. When you choose this subclass at 3rd level, you may spend 1 minute performing a rejuvenation ritual. Use the spirit tuning rules to rejuvenate exhausted ashes."
            },
            {
                name: "Empower Ash",
                level: 7,
                description: "Starting 7th level, spirits you call from ash are more resilient than normal. Any spirit you summon from a spirit calling bell gains two benefits:\n\n- The creature appears with more hit points than normal: 2 extra hit points per Hit Die it has.\n- The damage from its natural weapons is considered magical for the purpose of overcoming immunity and resistance to non-magical attacks and damage."
            },
            {
                name: "Baton Pass",
                level: 11,
                description: "Starting at 11 level, you may use your action to let a spirit you have summoned take an additional action before the end of its next turn."
            },
            {
                name: "Spirit Bond",
                level: 15,
                description: "The spirits dwelling in ash are willing to extinguish themselves to come to your aid. At 15th level, you can summon exhausted spirits without rejuvenating them first. If you do, the ash is destroyed and cannot be rejuvenated afterwards."
            }
        ]
    },
    {
        name: "Crafter",
        className: "Rogue",
        description: "A resourceful rogue archetype adept at foraging, improvising tools, and quick crafting to gain a tactical edge on the battlefield.",
        features: [
            {
                name: "Resourceful",
                level: 3,
                description: "Many of the materials in the lands between are used to craft secondary items that are useful to travelers. While recipes and cookbooks are helpful resources to learn new tricks, at 3rd level you learn to use materials you have in your possession as substitutes for ones you don't.\n\nWhen you use a crafting kit to make an item, you may substitute one common component in the recipe for another component of equal rarity. You may only substitute one type of component in a particular recipe, you must provide the rest as described. Your resourcefulness grows as you gain more experience in the Lands Between. At level 7, you may substitute an uncommon ingredient, at level 11 a rare ingredient, and at 15 a very rare ingredient. Only one ingredient can be substituted for a particular recipe, regardless of rarity."
            },
            {
                name: "Quick Deploy",
                level: 3,
                description: "At 3rd level, you may use a bonus action to use a crafted or consumable item if it would normally require an action. If you do not have a crafting kit when you pick this Archetype, you receive one now."
            },
            {
                name: "Quick Craft",
                level: 3,
                description: "Your expertise with a crafting kit allows you to make items much faster than others. As a bonus action, you can make a special Craft action. When you Craft, you can create an item that you know a recipe for as long as you have a Crafting Kit on your person."
            },
            {
                name: "Adept Forager",
                level: 9,
                description: "At 9th level, when traveling overland, you may roll twice on the material gathering table and gain the materials for both results."
            },
            {
                name: "Fine Craftsman",
                level: 9,
                description: "At 9th level, crafted and improvised weapons you wield are treated as finesse weapons as long as they lack the heavy property."
            },
            {
                name: "Master Craftsman",
                level: 17,
                description: "You've mastered using just enough materials to get the job you need done, and in doing so accumulated many half used materials. At 17th, you can use a Craft action to craft any item for which you have a recipe without using the necessary materials. This item is fragile and cobbled together, and thus is destroyed after you take a long rest. You may take this special Craft action once per long rest."
            }
        ]
    },
    {
        name: "Servant of Rot",
        className: "Sorcerer",
        description: "A sorcerer whose blood serves as a wellspring of scarlet rot. They are inured to poison and decay, using it to wither their foes.",
        features: [
            {
                name: "Arcane Aeonia",
                level: 1,
                description: "The scarlet rot swims in your blood, the very wellspring of your magic. At 1st level, when a creature begins its turn under the effects of a spell you are concentrating on, you can deal poison damage to it equal to your proficiency bonus as a free action."
            },
            {
                name: "Rotted Blood",
                level: 6,
                description: "The scarlet rot is your birthright, and it inures you to similar effects. At 6th level you gain resistance to poison and necrotic damage, as well as advantage on saving throws against becoming poisoned or afflicted by scarlet rot."
            },
            {
                name: "Now Rot!",
                level: 14,
                description: "Starting at 14th level, when you are hit by a melee attack, you can use your reaction to deal necrotic damage to the attacker. The damage equals your sorcerer level. The attacker must also make a Constitution saving throw against your sorcerer spell save DC. On a failed save, the attacker is poisoned until the end of its next turn."
            },
            {
                name: "Limb Atrophy",
                level: 14,
                description: "The rot takes to some more than others. At 14th level, you may choose to have one of your limbs rot completely. If one of your arms rots, you lose functionality of it completely and have disadvantage of Sleight of Hand checks. If one of your legs rots, your movement speed is halved and you have disadvantage on Dexterity saving throws.\n\nFinding or creating a prosthetic limb will fully replace your lost limb. If you wear a prosthetic arm, your Strength score increases by two. If you wear a prosthetic leg, your Dexterity score increases by two. You can only gain one of these benefits at a time, make this decision at the end of each long rest. You are also proficient with all prosthetic weapons."
            },
            {
                name: "Wave of Rot",
                level: 18,
                description: "At 18th level, the scarlet rot within you infects every spell you cast. When a creature fails a saving throw against a spell you cast, you can expend 2 sorcery points to infect it with scarlet rot. At the end of each of the creature's turns, it can make a Constitution saving throw against your spell save DC, ending the condition on a success."
            }
        ]
    },
    {
        name: "Dragon Communion",
        className: "Warlock",
        description: "A pact made by devouring the hearts of dragons. These warlocks channel draconic fire and magic, becoming ever more like the beasts they hunt.",
        features: [
            {
                name: "Expanded Spell List",
                level: 1,
                description: "When you take on this patron at 1st level, You can prepare Dragon Communion incantations in addition to sorceries. You also learn the *dragonclaw* spell."
            },
            {
                name: "Dragon Sense",
                level: 1,
                description: "At 1st level, you can project your senses to find new dragon hearts to offer in communion. As an action, you can focus on the dregs of dragon blood you consumed and sense any dragons in a 60-mile radius. You sense the nearest dragon if there are multiple, and you learn the distance and direction of that dragon. You also discovered the elemental damage type its breath weapon and melee attacks use."
            },
            {
                name: "Shape Flame",
                level: 6,
                description: "At 6th level, you can contain your magic when it would prefer to burst forth freely. When you cast a Dragon Communion incantation with an area of effect, you can reduce the area of effect in 5-foot increments down to a minimum of five feet. For instance, you can make a 60-foot cone affect a 30-foot cone area instead, or a 5-foot cone at a minimum. If you reduce the area to the minimum, you can instead have the spell target a single creature within 5 feet of you. If you do, the target has disadvantage on saving throws against the spell."
            },
            {
                name: "Second Head of the Dragon",
                level: 14,
                description: "At 14th level, you can take hold of the lingering magic left over from channeling the dragon's blood. When you cast a Dragon Communion incantation with an instantaneous duration, you can cast the same incantation on your next turn without expending a spell slot/point.\n\nYou can use this ability once per short rest."
            },
            {
                name: "Heart Hunter",
                level: 18,
                description: "At 18th level, having claimed the hearts of many dragons, you learn to exploit their magic against their kin. Your spells ignore damage resistances and immunities of dragons. Dragon hearts you offer in exchange for dragon communion incantations are treated as if they were two hearts instead."
            }
        ]
    },
    {
        name: "School of Glintstone",
        className: "Wizard",
        description: "Scholars of Raya Lucaria who dive deep into the primal current and mysteries of the stars, wielding potent force magic and foresight.",
        features: [
            {
                name: "Devoted Pupil",
                level: 2,
                description: "Your studies at Raya Lucaria may be long passed, but the knowledge you've gleaned during your time there remains with you. At 2nd level, you gain proficiency in two of the following skills: Arcana, History, Nature, or Religion. You also add the *identify* spell to your spell book."
            },
            {
                name: "Spell Delver",
                level: 2,
                description: "At 2nd level, you can learn from other mages during brief bursts of inspiration. As a reaction to a creature you see casting a sorcery, you can make an Arcana check to identify and copy the spell. The DC of the check is 10 + the spell's level. On a success, you can immediately prepare the spell and it doesn't count against the number of spells you can prepare each day until you finish a long rest. You can spend an hour before you finish a long rest to copy the spell into your spellbook without spending runes.\n\nIf you choose to copy the spell, you cannot use this ability until you gain a new Wizard level."
            },
            {
                name: "Portent",
                level: 2,
                description: "Starting at 2nd level when you choose this school, glimpses of the future begin to press in on your awareness. When you finish a long rest, roll two d20s and record the numbers rolled. You can replace any attack roll, saving throw, or ability check made by you or a creature that you can see with one of these foretelling rolls. You must choose to do so before the roll, and you can replace a roll in this way only once per turn.\n\nEach foretelling roll can be used only once. When you finish a long rest, you lose any unused foretelling rolls."
            },
            {
                name: "Glintmage Adept",
                level: 6,
                description: "At 6th level, when you cast a spell that creates two or more projectiles or glintblades, you may create an additional one."
            },
            {
                name: "Starbound Fate",
                level: 10,
                description: "The stars alter the fate of the Carian royal family, and all glintstone mages to an extent. At 10th level, as an action once per long rest, you can change any of your prepared spells in the same manner that you would after finishing a long rest. This feature is not available to you if the stars' motion is still arrested."
            },
            {
                name: "Glimpse the Primeval Current",
                level: 14,
                description: "Following in the steps of some of the most powerful glintstone sorcerers, at 14th level you can stare into the primeval current to empower your magic. As part of casting a spell of 1st level or higher, you may cast it as if you used a 9th-level spell slot/points. This does not allow you to cast 9th-level spells unless you have the caster levels otherwise required. You may use this ability once per long rest without additional consequences. If you use it again before finishing a long rest, you gain a level of exhaustion and your Sanity score is reduced by 1."
            }
        ]
    }
];